services:
  postgres:
    image: postgres:16-alpine
    container_name: laundrot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laundrot
    ports:
      - "51582:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
